/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":parser"))
}

application {
    mainClass = "com.newardassociates.tinylang.AppKt"
}
